### ISSUE TITLE
What happened to your x10bridge project?

### ISSUE THREAD

**Issue by famewolf** [statusbits/smartthings#12]
I followed a youtube video you did to a broken link.  I have the old cm17a firecracker system which came with the same remote and rf receiver kit.   I also have the smartthings hub.   I still have some x10 modules around and would like to put them to use until they finally die and are replaced by cheaper newer replacements.   

Thank you for your time.   https://www.youtube.com/watch?v=laCar-03Jq4

**Comment by statusbits** [comment]
X10 Bridge used Mochad server to interface with CM17. Mochad uses TCP sockets which are not supported by SmartThings. As a result, it did not work reliably and I eventually scrapped the project and got rid of my X10 switches.

**Comment by ssshake** [comment]
I've installed your old code and I know you don't support it. But when I try to install the device handler and bridge it never shows up in the app. Could you please tell me the steps I'm supposed to take after creating the handler and bridge in the ide? aka what is the deploy process. Thanks.
