### ISSUE TITLE
Pollster is not working for a couple people at least as of 20160630

### ISSUE THREAD

**Issue by kevin789900** [statusbits/smartthings#14]
I get Error Saving Page when I try to change settings.  It doesn't seem to be running at all unless I press the SmartApp button.  I added some logging to Google Sheets and they aren't showing up.https://community.smartthings.com/t/pollster-a-smartthings-polling-daemon/3447/342?u=kevin

**Comment by statusbits** [comment]
Probably was an ST platform issue.
