### ISSUE TITLE
Disable logging to 'Recently' in the App

### ISSUE THREAD

**Issue by icepicknz** [statusbits/smartthings#16]
Hi,

I was wondering if it were possible to disable the debug entry to 'Recently' on things, i.e. so it doesn't show 'Polister' each time it polls a device. It would be handy to be able to disable this on a per group basis so I can still go to a device and see when it was turned on or off rather than seeing Polister entries for pages and pages.

Many thanks and great work!

**Comment by statusbits** [comment]
Those are not debug messages. They're pushed by SmartThings platform and I have no control over it, unfortunately.
