### ISSUE TITLE
When pressing + on heat the heat temp will drop out of blue, have to press + again

### ISSUE THREAD

**Issue by emilkacp** [statusbits/smartthings#17]
The only issue I have seen is when increasing the heat it will drop to a lower level.  So your basically fighting it to increase heat.  The room temperature can be 75 and the heat set to 72, so if you want to increase to 78 you start to hit the +.  You press + 4 times to get 76 but it will then change to 72 or 73.  Press + again from the changed temperature and it changes again.  So you are constantly fighting to reach the correct temperature and the heater will turn on / off depending what it drops to.

Not using the cooling portion so unable to test.

**Comment by statusbits** [comment]
Sending commands to the thermostat takes a couple of seconds. You need to wait for a few seconds after pressing "+" or "-" until the temperature adjustment is complete.
