### ISSUE TITLE
Asking for current temperature always returns 70 degrees. Changing temperature works fine. 

### ISSUE THREAD

**Issue by wwahmed** [statusbits/smartthings#20]
Thanks a lot for providing this excellent utility allowing me to not replace my TWO thermostats. I just got them to work with SmartThings tonight. 

I have set their IPs and can change the target temperature fine (it takes about a second, which is pretty good). 

However, I am experiencing an issue on both: Asking for current setting (via Google Home) always returns "Cooling to 70 degrees."

However, the UI in SmartThings shows the correct cooling target temperature. I am going to investigate the integration between SmartThings and GoogleHome but wanted to share this issue here in case someone else experienced this and has a tip.

**Comment by statusbits** [comment]
SmartThings is shutting down its Groovy-based platform at the end of 2022. This project is no longer maintained.
