### ISSUE TITLE
Will this stop working after the migration from Classic?

### ISSUE THREAD

**Issue by focuspulling** [statusbits/smartthings#23]
It's mandatory in a few weeks. Is my Radio Thermostat via Wi-Fi going to become totally worthless?

**Comment by statusbits** [comment]
Not at all. The device handler still works after migration.

**Comment by focuspulling** [comment]
> Not at all. The device handler still works after migration.

Thank you very much for your assurance; I was anxious about pressing go to the migration, but after reading your assurance, I let it happen and yes, it still works.  Big sigh of relief.
