### ISSUE TITLE
Smartthings Celsius to Fahrenheit Error

### ISSUE THREAD

**Issue by scooby860** [statusbits/smartthings#3]
hi all:

getting an error when trying to change temp in Celsius:

 6:47:30 PM EST: error groovy.lang.MissingMethodException: No signature of method: script1424908044784743819686.temperatureCtoF() is applicable for argument types: (java.lang.Double) values: [19.600000381469727] @ line 346

the fan an mode seem to work fine in celsius. Also, the colour temp is always a dark coloured blue. I presume it'a quick fix in getting the Celsius to Fahrenheit to convert properly. 

I appreciate ANY help on this:)

Thanks!

**Comment by statusbits** [comment]
Fixed in version 2.0.0.
