### ISSUE TITLE
Trouble installing: Won't "compile"

### ISSUE THREAD

**Issue by eyv** [statusbits/smartthings#5]
When pasting the code EXACTLY into the web IDE, I get the following:

groovy.lang.MissingMethodException: No signature of method: script1437243857324561763135.metadata() is applicable for argument types: (script1437243857324561763135$_run_closure2) values: [script1437243857324561763135$_run_closure2@568820a]
Possible solutions: getMetadata(), getState(), setState(java.lang.Object), metaClass(groovy.lang.Closure) @ line 35

So, it appears there's something wrong with the metadata block, but I can't for the life of me find the problem. Thoughts?

**Comment by statusbits** [comment]
What exactly are you trying to install?

**Comment by eyv** [comment]
The VLC_thing script

**Comment by statusbits** [comment]
VLC Thing is a device handler. Make sure you're not trying to install it as a smart app. I believe this is what you're doing.

**Comment by eyv** [comment]
Indeed. Thank you!
