### ISSUE TITLE
fix humidity to show 0-100%

### ISSUE THREAD

**Issue by tonesto7** [statusbits/smartthings#7]
This is working:

def onHumidity(evt) {
    LOG("onHumidity($evt.value)")
    def device = evt.device
    def metricId = getMetricId(device.id, "humidity")
    if (!metricId) {
        createHumidityMetric(device)
    } else {
        def data = [
            value: (evt.value.toInteger() /100).toString()
        ]

```
    apiUpdateValue(metricId, data)
}
```

}

**Comment by statusbits** [comment]
SmartThings is shutting down its Groovy-based platform at the end of 2022. This project is no longer maintained.
