### ISSUE TITLE
Not Skipping Event Sound

### ISSUE THREAD

**Issue by ryinnthedk** [statusbits/smartthings#8]
I am playing with your VLC Things.  It's awesome, for starters.  Noticing an issue though.  I set it to play a custom track found in my VLC library... no problems going in and selecting that track.  When I set it to play piano, and then alternatively say OR play my track... it still plays the piano and doesn't play my track:

![image](https://cloud.githubusercontent.com/assets/15601804/10872443/26893094-80bf-11e5-9dbd-d82837ab7c48.png)

**Comment by statusbits** [comment]
SmartThings is shutting down its Groovy-based platform at the end of 2022. This project is no longer maintained.
